### ISSUE TITLE
Development: App Name

### ISSUE THREAD

**Issue by LcNguyn** [nguyenducminhtam/sepm-snapie#20]
While a name for a mobile app is not a guarantee of success, the correct one may enhance our final score. And yep, our app name is a must for our currently-unnamed app. Make sure that our research will not go unrewarded by giving our kid a huge name.

Our app name should provide some indication of its functionality. Unique and different from other names, of course. A wrong app name can make our app to be faded or lost in a bunch of other applications.

#Technology #Education #Kid #Explore is our app keywords. From them, we can come up with some relatively cool names.

**Comment by LcNguyn** [comment]
<p><a href="https://api.gh-polls.com/poll/01E3Y6AVGKP6GJ9XV0GRKHCWY3/Techi/vote"><img src="https://api.gh-polls.com/poll/01E3Y6AVGKP6GJ9XV0GRKHCWY3/Techi" alt=""></a>
<a href="https://api.gh-polls.com/poll/01E3Y6AVGKP6GJ9XV0GRKHCWY3/EduTech/vote"><img src="https://api.gh-polls.com/poll/01E3Y6AVGKP6GJ9XV0GRKHCWY3/EduTech" alt=""></a>
<a href="https://api.gh-polls.com/poll/01E3Y6AVGKP6GJ9XV0GRKHCWY3/EdTech/vote"><img src="https://api.gh-polls.com/poll/01E3Y6AVGKP6GJ9XV0GRKHCWY3/EdTech" alt=""></a>
<a href="https://api.gh-polls.com/poll/01E3Y6AVGKP6GJ9XV0GRKHCWY3/TechEd/vote"><img src="https://api.gh-polls.com/poll/01E3Y6AVGKP6GJ9XV0GRKHCWY3/TechEd" alt=""></a>
<a href="https://api.gh-polls.com/poll/01E3Y6AVGKP6GJ9XV0GRKHCWY3/TecKid/vote"><img src="https://api.gh-polls.com/poll/01E3Y6AVGKP6GJ9XV0GRKHCWY3/TecKid" alt=""></a></p>

**Comment by LcNguyn** [comment]
@trungduong0103 @s3687636 @thienhieu215 can I have ur vote plz !!!

**Comment by trungduong0103** [comment]
why must there be a tech and an edu in our name ? Uber doesn't have tech or edu in their name, neither is youtube and other apps

**Comment by trungduong0103** [comment]
> why must there be a tech and an edu in our name ? Uber doesn't have tech or edu in their name, neither is youtube and other apps

Nevermind, I saw the hashtags. But still, I’d love to see an app name that has neither tech or edu in it. We’re not a school lol.

**Comment by trungduong0103** [comment]
I accidentally voted 3 times

**Comment by thienhieu215** [comment]
I voted

**Comment by s3687636** [comment]
> why must there be a tech and an edu in our name ? Uber doesn't have tech or edu in their name, neither is youtube and other apps

yeah, i agree with this. Why bother Tech or Edu?

**Comment by s3687636** [comment]
TEKE (tech, edu, kid, explr) ?

**Comment by trungduong0103** [comment]
Other names are greatly appreciated if you can brainstorm more

**Comment by LcNguyn** [comment]
Simplicity. Youtube, Facebook's target are teenagers, adults whose curiosity is definitely greater than a kid or a mother. So their name is more abstract. Btw, Facebook and Youtube are made the same as our way (face/book, you/tube).
Neither of the naming styles is worse, but which approaches users more?
https://www.thinklions.com/blog/how-to-name-an-app/
https://www.creativebloq.com/apps/tips-naming-app-9112818

**Comment by LcNguyn** [comment]
But sure, I will try to brainstorm more names. But for now, Techi has the most vote.

**Comment by LcNguyn** [comment]
<p><a href="https://api.gh-polls.com/poll/01E40Q1F1BBJK9ZWQXFP95HGWK/Xplore%20/vote"><img src="https://api.gh-polls.com/poll/01E40Q1F1BBJK9ZWQXFP95HGWK/Xplore%20" alt=""></a>
<a href="https://api.gh-polls.com/poll/01E40Q1F1BBJK9ZWQXFP95HGWK/Hipolar/vote"><img src="https://api.gh-polls.com/poll/01E40Q1F1BBJK9ZWQXFP95HGWK/Hipolar" alt=""></a>
<a href="https://api.gh-polls.com/poll/01E40Q1F1BBJK9ZWQXFP95HGWK/%20%20TEKE/vote"><img src="https://api.gh-polls.com/poll/01E40Q1F1BBJK9ZWQXFP95HGWK/%20%20TEKE" alt=""></a>
<a href="https://api.gh-polls.com/poll/01E40Q1F1BBJK9ZWQXFP95HGWK/%20Edcam/vote"><img src="https://api.gh-polls.com/poll/01E40Q1F1BBJK9ZWQXFP95HGWK/%20Edcam" alt=""></a></p>

**Comment by LcNguyn** [comment]
@trungduong0103 @thienhieu215 @s3687636

**Comment by trungduong0103** [comment]
We all agreed with Snapie
