### ISSUE TITLE
phase 1: research tools [s3698997]

### ISSUE THREAD

**Issue by trungduong0103** [nguyenducminhtam/sepm-snapie#8]
- [x] Read Google Vision APIs
- [x] Set up an endpoint to analyze image
- [x] Learn React Native
    * Create Hello World App.
    * Run App on iOS simulator.
    * Create Shopping List App.
- [x] Learn & Adopt Redux into React Native App

**Comment by trungduong0103** [comment]
Cloud Vision API docs: https://cloud.google.com/vision/docs

**Comment by trungduong0103** [comment]
- [x]  Set up an endpoint to analyze image

Image: 
![cat](https://user-images.githubusercontent.com/15820443/76919682-29c44f80-68fc-11ea-9bae-73bb8aba07f7.jpg)

Steps to reproduce: 
1. Create new Gcloud Project
2. Follow this page to setup Vision API **https://cloud.google.com/vision/docs/setup**
3. At the end of the setup, download service key, the format is JSON.
4. Create a new folder, use firebase init and choose "Functions: Configure and deploy Cloud Functions"
5. Go to functions directory inside created folder, run **npm i @google-cloud/vision**
6. Put the image and the service key inside your functions folder, right next to index.js file
7. Use sample code:

`const functions = require('firebase-functions');

exports.testVision = functions.https.onRequest((request, response) => {
    console.log('executing function...');
    const vision = require('@google-cloud/vision');
    // ImageAnnotatorClinet does not require keyFilename options if you exported your key to PATH
    const client = new vision.ImageAnnotatorClient({keyFilename: './environments/vision-api-key.json'});

    return client.labelDetection('./cat.jpg')
        .then((result) => {
            console.log(result);
            return response.send(result);
        })
        .catch((err) => {
            response.send(err);
        })
});`

8. Run firebase serve, there should be a link given to you, mine was 
http://localhost:5000/rmit-sepm/us-central1/testVision

9. Test your functions using Postman, cURL...

End result:
`
[
    {
        "faceAnnotations": [],
        "landmarkAnnotations": [],
        "logoAnnotations": [],
        "labelAnnotations": [
            {
                "locations": [],
                "properties": [],
                "mid": "/m/01yrx",
                "locale": "",
                "description": "Cat",
                "score": 0.9959855675697327,
                "confidence": 0,
                "topicality": 0.9959855675697327,
                "boundingPoly": null
            },
            {
                "locations": [],
                "properties": [],
                "mid": "/m/04rky",
                "locale": "",
                "description": "Mammal",
                "score": 0.9890478253364563,
                "confidence": 0,
                "topicality": 0.9890478253364563,
                "boundingPoly": null
            },
            {
                "locations": [],
                "properties": [],
                "mid": "/m/07k6w8",
                "locale": "",
                "description": "Small to medium-sized cats",
                "score": 0.9785529971122742,
                "confidence": 0,
                "topicality": 0.9785529971122742,
                "boundingPoly": null
            },
            {
                "locations": [],
                "properties": [],
                "mid": "/m/01l7qd",
                "locale": "",
                "description": "Whiskers",
                "score": 0.9746754765510559,
                "confidence": 0,
                "topicality": 0.9746754765510559,
                "boundingPoly": null
            }
        ],
        "textAnnotations": [],
        "localizedObjectAnnotations": [],
        "safeSearchAnnotation": null,
        "imagePropertiesAnnotation": null,
        "error": null,
        "cropHintsAnnotation": null,
        "fullTextAnnotation": null,
        "webDetection": null,
        "productSearchResults": null,
        "context": null
    }
]
`
I omitted some results

**Comment by trungduong0103** [comment]
- [x] Learn React Native
    * Create Hello World App.
    * Run App on iOS simulator.
    * Create Shopping List App.

**Comment by s3687636** [comment]
can you test the demo app with real devices (iphone, android..)?

**Comment by trungduong0103** [comment]
> can you test the demo app with real devices (iphone, android..)?

I only tested the app on iPhone X simulator, but I'm sure it will work with any  android and iPhone devices. I will buy a Type-C cord later to test on my own device.

**Comment by s3687636** [comment]
the android simulator setting is fix to only one kind of simulator. I have tested it out.
anyway, we will try it on real devices.

**Comment by trungduong0103** [comment]
> the android simulator setting is fix to only one kind of simulator. I have tested it out.
> anyway, we will try it on real devices.

nice !
